### PR TITLE
update ctools.data

### PR DESCRIPTION
**Pull request by ain-soph**
Mainly some format and type annotation updates.  
And some small bug fixes:
- remove `from torch._six import container_abcs, string_classes, int_classes` and instead use (for pytorch 1.9.0 compatibility)
```python3
import collections.abc as container_abcs
from torch._six import string_classes
int_classes = (bool, int)
```
- A bug reported with `TODO` in comment

```python3
data = self.data_source(self.batch_size, paths)  # TODO(Local State) `paths` is not defined
```
- fix a return bug in `ctools.data.structure.buffer.PrioritizedBuffer._sample_check `

### CODE REVIEW

**Comment by PaParaZz1** [comment]
Codes in `ctools` will be updated in next weeks. My advice is that you can pay more attention to `distar` directory, especially those parts which is easy to misunderstand, and you can provide some comments about which parts are more necessary to add some tables and graphs.

**Comment by ain-soph** [comment]
@PaParaZz1 

Ok. You may fix the 3 small bugs I proposed. And hope the maintainers can set several issues and roadmaps to guide others which part needs help.

**Comment by upia99** [comment]
> @PaParaZz1
> 
> Ok. You may fix the 3 small bugs I proposed. And hope the maintainers can set several issues and roadmaps to guide others which part needs help.

We will release training code around August. It would be nice to have your help then. Just play around now!

**Comment by ain-soph** [comment]
emmm. It’s already merged?

I have to say that I haven’t fully tested my modification, since there is no unit test code. 

please check it with care.

**Pull request merged**
